#!/usr/bin/env python3
"""
MBTI Questions Bank - Portuguese Brazilian Translation
Four versions: 70, 93, 144, 200 questions
Tradução completa do banco original chinês para português brasileiro.
"""

QUESTIONS = {
    # ========== VERSION 70 (Quick) ==========
    70: [
        # Energy - EI (17 questions)
        {"id": 1, "dimension": "EI", "option_a": "Em festas, você geralmente...", "option_b": "conversa animadamente com muitas pessoas e ganha energia com isso", "preference_a": "E"},
        {"id": 2, "dimension": "EI", "option_a": "Quando está sozinho, você se sente...", "option_b": "recarregado e em paz", "preference_a": "I"},
        {"id": 3, "dimension": "EI", "option_a": "Você prefere...", "option_b": "conversar com pessoas", "preference_a": "E"},
        {"id": 4, "dimension": "EI", "option_a": "Você tende a...", "option_b": "agir primeiro e pensar depois", "preference_a": "E"},
        {"id": 5, "dimension": "EI", "option_a": "Você prefere...", "option_b": "trabalhar em grupo", "preference_a": "E"},
        {"id": 6, "dimension": "EI", "option_a": "Eventos sociais fazem você se sentir...", "option_b": "cheio de energia", "preference_a": "E"},
        {"id": 7, "dimension": "EI", "option_a": "Você prefere...", "option_b": "discussões em equipe", "preference_a": "E"},
        {"id": 8, "dimension": "EI", "option_a": "No seu tempo livre, você prefere...", "option_b": "sair com amigos", "preference_a": "E"},
        {"id": 9, "dimension": "EI", "option_a": "Você ganha energia através...", "option_b": "da interação com pessoas", "preference_a": "E"},
        {"id": 10, "dimension": "EI", "option_a": "Você prefere...", "option_b": "sair e socializar", "preference_a": "E"},
        {"id": 11, "dimension": "EI", "option_a": "Ficar sozinho faz você...", "option_b": "recuperar suas energias", "preference_a": "I"},
        {"id": 12, "dimension": "EI", "option_a": "Você aprecia mais...", "option_b": "conversas profundas individuais", "preference_a": "I"},
        {"id": 13, "dimension": "EI", "option_a": "Você tende a...", "option_b": "pensar antes de agir", "preference_a": "I"},
        {"id": 14, "dimension": "EI", "option_a": "Você prefere...", "option_b": "trabalhar sozinho", "preference_a": "I"},
        {"id": 15, "dimension": "EI", "option_a": "Eventos sociais fazem você se sentir...", "option_b": "cansado", "preference_a": "I"},
        {"id": 16, "dimension": "EI", "option_a": "Você prefere...", "option_b": "ambientes tranquilos", "preference_a": "I"},
        {"id": 17, "dimension": "EI", "option_a": "No seu tempo livre, você prefere...", "option_b": "ler ou refletir sozinho", "preference_a": "I"},
        
        # Information - SN (18 questions)
        {"id": 18, "dimension": "SN", "option_a": "Você valoriza mais...", "option_b": "dados e fatos concretos", "preference_a": "S"},
        {"id": 19, "dimension": "SN", "option_a": "Você confia mais em...", "option_b": "informações específicas", "preference_a": "S"},
        {"id": 20, "dimension": "SN", "option_a": "Você tende a...", "option_b": "prestar atenção nos detalhes", "preference_a": "S"},
        {"id": 21, "dimension": "SN", "option_a": "Você prefere...", "option_b": "métodos já conhecidos", "preference_a": "S"},
        {"id": 22, "dimension": "SN", "option_a": "Você foca mais em...", "option_b": "situações reais e concretas", "preference_a": "S"},
        {"id": 23, "dimension": "SN", "option_a": "Você prefere...", "option_b": "seguir um plano estabelecido", "preference_a": "S"},
        {"id": 24, "dimension": "SN", "option_a": "Você prefere...", "option_b": "resolver problemas práticos", "preference_a": "S"},
        {"id": 25, "dimension": "SN", "option_a": "Você valoriza mais...", "option_b": "experiência e fatos", "preference_a": "S"},
        {"id": 26, "dimension": "SN", "option_a": "Você tende a...", "option_b": "usar processos estabelecidos", "preference_a": "S"},
        {"id": 27, "dimension": "SN", "option_a": "Você confia mais em...", "option_b": "experiências práticas", "preference_a": "S"},
        {"id": 28, "dimension": "SN", "option_a": "Você foca mais no...", "option_b": "aqui e agora", "preference_a": "S"},
        {"id": 29, "dimension": "SN", "option_a": "Você prefere...", "option_b": "acreditar no que vê", "preference_a": "S"},
        {"id": 30, "dimension": "SN", "option_a": "Você prefere...", "option_b": "possibilidades e imaginação", "preference_a": "N"},
        {"id": 31, "dimension": "SN", "option_a": "Você confia mais em...", "option_b": "sua intuição", "preference_a": "N"},
        {"id": 32, "dimension": "SN", "option_a": "Você tende a...", "option_b": "observar o quadro geral", "preference_a": "N"},
        {"id": 33, "dimension": "SN", "option_a": "Você prefere...", "option_b": "ideias novas e inovadoras", "preference_a": "N"},
        {"id": 34, "dimension": "SN", "option_a": "Você foca mais em...", "option_b": "possibilidades futuras", "preference_a": "N"},
        {"id": 35, "dimension": "SN", "option_a": "Você prefere...", "option_b": "experimentar novas abordagens", "preference_a": "N"},
        
        # Decisions - TF (18 questions)
        {"id": 36, "dimension": "TF", "option_a": "Ao tomar decisões, você valoriza mais...", "option_b": "lógica e consistência", "preference_a": "T"},
        {"id": 37, "dimension": "TF", "option_a": "Você tende a...", "option_b": "tratar todos com justiça e imparcialidade", "preference_a": "T"},
        {"id": 38, "dimension": "TF", "option_a": "Você valoriza mais...", "option_b": "princípios e regras", "preference_a": "T"},
        {"id": 39, "dimension": "TF", "option_a": "Ao decidir, você...", "option_b": "baseia-se na análise dos fatos", "preference_a": "T"},
        {"id": 40, "dimension": "TF", "option_a": "Você tende a...", "option_b": "usar o raciocínio lógico", "preference_a": "T"},
        {"id": 41, "dimension": "TF", "option_a": "Você valoriza mais...", "option_b": "análises corretas e precisas", "preference_a": "T"},
        {"id": 42, "dimension": "TF", "option_a": "Ao decidir, você...", "option_b": "segue a lógica", "preference_a": "T"},
        {"id": 43, "dimension": "TF", "option_a": "Você dá mais peso a...", "option_b": "razões objetivas", "preference_a": "T"},
        {"id": 44, "dimension": "TF", "option_a": "Você tende a...", "option_b": "apontar erros e inconsistentes", "preference_a": "T"},
        {"id": 45, "dimension": "TF", "option_a": "Você valoriza mais...", "option_b": "a verdade", "preference_a": "T"},
        {"id": 46, "dimension": "TF", "option_a": "Ao tomar decisões, você valoriza mais...", "option_b": "o impacto nas pessoas", "preference_a": "F"},
        {"id": 47, "dimension": "TF", "option_a": "Você tende a...", "option_b": "considerar os sentimentos alheios", "preference_a": "F"},
        {"id": 48, "dimension": "TF", "option_a": "Você valoriza mais...", "option_b": "relacionamentos interpessoais", "preference_a": "F"},
        {"id": 49, "dimension": "TF", "option_a": "Ao decidir, você...", "option_b": "leva em conta fatores emocionais", "preference_a": "F"},
        {"id": 50, "dimension": "TF", "option_a": "Você tende a...", "option_b": "ser compreensivo com os outros", "preference_a": "F"},
        {"id": 51, "dimension": "TF", "option_a": "Você valoriza mais...", "option_b": "harmonia", "preference_a": "F"},
        {"id": 52, "dimension": "TF", "option_a": "Ao decidir, você...", "option_b": "considera seus valores pessoais", "preference_a": "F"},
        {"id": 53, "dimension": "TF", "option_a": "Você valoriza mais...", "option_b": "conexões emocionais", "preference_a": "F"},
        
        # Structure - JP (17 questions)
        {"id": 54, "dimension": "JP", "option_a": "Você prefere...", "option_b": "uma vida planejada e organizada", "preference_a": "J"},
        {"id": 55, "dimension": "JP", "option_a": "Você tende a...", "option_b": "seguir um cronograma", "preference_a": "J"},
        {"id": 56, "dimension": "JP", "option_a": "Você prefere...", "option_b": "decidir e executar", "preference_a": "J"},
        {"id": 57, "dimension": "JP", "option_a": "Você prefere...", "option_b": "planejar com antecedência", "preference_a": "J"},
        {"id": 58, "dimension": "JP", "option_a": "Você prefere...", "option_b": "organização e ordem", "preference_a": "J"},
        {"id": 59, "dimension": "JP", "option_a": "Você tende a...", "option_b": "focar em concluir objetivos", "preference_a": "J"},
        {"id": 60, "dimension": "JP", "option_a": "Você prefere...", "option_b": "ser organizado", "preference_a": "J"},
        {"id": 61, "dimension": "JP", "option_a": "Você prefere...", "option_b": "entregar tarefas no prazo", "preference_a": "J"},
        {"id": 62, "dimension": "JP", "option_a": "Você valoriza mais...", "option_b": "planos e agendas", "preference_a": "J"},
        {"id": 63, "dimension": "JP", "option_a": "Você tende a...", "option_b": "cumprir prazos", "preference_a": "J"},
        {"id": 64, "dimension": "JP", "option_a": "Você prefere...", "option_b": "ser flexível e espontâneo", "preference_a": "P"},
        {"id": 65, "dimension": "JP", "option_a": "Você tende a...", "option_b": "improvisar conforme necessário", "preference_a": "P"},
        {"id": 66, "dimension": "JP", "option_a": "Você prefere...", "option_b": "manter suas opções abertas", "preference_a": "P"},
        {"id": 67, "dimension": "JP", "option_a": "Você prefere...", "option_b": "esperar para ver o que acontece", "preference_a": "P"},
        {"id": 68, "dimension": "JP", "option_a": "Você prefere...", "option_b": "agir por impulso", "preference_a": "P"},
        {"id": 69, "dimension": "JP", "option_a": "Você tende a...", "option_b": "se adaptar às mudanças", "preference_a": "P"},
        {"id": 70, "dimension": "JP", "option_a": "Você prefere...", "option_b": "decisões de última hora", "preference_a": "P"},
    ],
}

# Add more questions for version 93 (extend with 23 more questions)
QUESTIONS[93] = QUESTIONS[70].copy() + [
    {"id": 71, "dimension": "EI", "option_a": "Em eventos grandes, você geralmente...", "option_b": "faz novas amizades espontaneamente", "preference_a": "E"},
    {"id": 72, "dimension": "EI", "option_a": "Você prefere...", "option_b": "ser o centro das atenções", "preference_a": "E"},
    {"id": 73, "dimension": "SN", "option_a": "Você confia mais em...", "option_b": "métodos já comprovados", "preference_a": "S"},
    {"id": 74, "dimension": "SN", "option_a": "Você tende a...", "option_b": "focar em resultados práticos", "preference_a": "S"},
    {"id": 75, "dimension": "TF", "option_a": "Ao decidir, você...", "option_b": "primeiro analisa prós e contras", "preference_a": "T"},
    {"id": 76, "dimension": "TF", "option_a": "Você tende a...", "option_b": "manter a objetividade", "preference_a": "T"},
    {"id": 77, "dimension": "JP", "option_a": "Você prefere...", "option_b": "trabalhar com listas de tarefas", "preference_a": "J"},
    {"id": 78, "dimension": "JP", "option_a": "Você tende a...", "option_b": "se preparar com antecedência", "preference_a": "J"},
    {"id": 79, "dimension": "EI", "option_a": "Você prefere...", "option_b": "improvisar na hora", "preference_a": "E"},
    {"id": 80, "dimension": "SN", "option_a": "Você foca mais em...", "option_b": "exemplos concretos", "preference_a": "S"},
    {"id": 81, "dimension": "TF", "option_a": "Você valoriza mais...", "option_b": "eficiência e lógica", "preference_a": "T"},
    {"id": 82, "dimension": "JP", "option_a": "Você prefere...", "option_b": "prazos bem definidos", "preference_a": "J"},
    {"id": 83, "dimension": "EI", "option_a": "Em uma equipe, você...", "option_b": "compartilha suas ideias abertamente", "preference_a": "E"},
    {"id": 84, "dimension": "SN", "option_a": "Você confia mais em...", "option_b": "fatos e dados concretos", "preference_a": "S"},
    {"id": 85, "dimension": "TF", "option_a": "Você acredita que... é mais importante", "option_b": "justiça do que compaixão", "preference_a": "T"},
    {"id": 86, "dimension": "JP", "option_a": "Você gosta de...", "option_b": "planos bem definidos", "preference_a": "J"},
    {"id": 87, "dimension": "EI", "option_a": "Você obtém inspiração através...", "option_b": "de sessões de brainstorming em grupo", "preference_a": "E"},
    {"id": 88, "dimension": "SN", "option_a": "Você prefere...", "option_b": "passo a passo", "preference_a": "S"},
    {"id": 89, "dimension": "TF", "option_a": "Ao decidir, você...", "option_b": "prioriza princípios éticos", "preference_a": "T"},
    {"id": 90, "dimension": "JP", "option_a": "Você prefere...", "option_b": "ter metas bem claras", "preference_a": "J"},
    {"id": 91, "dimension": "SN", "option_a": "Você foca mais em...", "option_b": "fatos do momento presente", "preference_a": "S"},
    {"id": 92, "dimension": "TF", "option_a": "Você acredita que... é mais importante", "option_b": "integridade do que diplomacia", "preference_a": "T"},
    {"id": 93, "dimension": "JP", "option_a": "Você gosta de...", "option_b": "trabalhar sob pressão de prazos", "preference_a": "J"},
]

# Add more questions for version 144 (extend with 51 more questions)
QUESTIONS[144] = QUESTIONS[93].copy() + [
    {"id": 94, "dimension": "EI", "option_a": "Você prefere...", "option_b": "falar em público para grupos grandes", "preference_a": "E"},
    {"id": 95, "dimension": "SN", "option_a": "Você confia mais em...", "option_b": "coisas que vê com os próprios olhos", "preference_a": "S"},
    {"id": 96, "dimension": "TF", "option_a": "Ao decidir, você...", "option_b": "considera como isso afeta as pessoas", "preference_a": "F"},
    {"id": 97, "dimension": "JP", "option_a": "Você prefere...", "option_b": "tomar decisões e depois agir", "preference_a": "J"},
    {"id": 98, "dimension": "EI", "option_a": "Socializar faz você se sentir...", "option_b": "com a mente mais ativa", "preference_a": "E"},
    {"id": 99, "dimension": "SN", "option_a": "Você foca mais em...", "option_b": "detalhes específicos", "preference_a": "S"},
    {"id": 100, "dimension": "TF", "option_a": "Você valoriza mais...", "option_b": "o pensamento lógico e estruturado", "preference_a": "T"},
    {"id": 101, "dimension": "JP", "option_a": "Você gosta de...", "option_b": "tudo bem organizado e no lugar", "preference_a": "J"},
    {"id": 102, "dimension": "EI", "option_a": "Você tende a...", "option_b": "se expressar abertamente", "preference_a": "E"},
    {"id": 103, "dimension": "SN", "option_a": "Você prefere...", "option_b": "o que já foi testado e aprovado", "preference_a": "S"},
    {"id": 104, "dimension": "TF", "option_a": "Você acredita que... é mais importante", "option_b": "a justiça imparcial", "preference_a": "T"},
    {"id": 105, "dimension": "JP", "option_a": "Você tende a...", "option_b": "seguir o que foi planejado", "preference_a": "J"},
    {"id": 106, "dimension": "EI", "option_a": "Você gosta de...", "option_b": "liderar discussões em grupo", "preference_a": "E"},
    {"id": 107, "dimension": "SN", "option_a": "Você foca mais em...", "option_b": "informações já disponíveis", "preference_a": "S"},
    {"id": 108, "dimension": "TF", "option_a": "Ao decidir, você...", "option_b": "se baseia em análises objetivas", "preference_a": "T"},
    {"id": 109, "dimension": "JP", "option_a": "Você prefere...", "option_b": "ter uma direção bem clara", "preference_a": "J"},
    {"id": 110, "dimension": "EI", "option_a": "Você ganha energia através...", "option_b": "da interação com os outros", "preference_a": "E"},
    {"id": 111, "dimension": "SN", "option_a": "Você prefere...", "option_b": "acreditar em fatos concretos", "preference_a": "S"},
    {"id": 112, "dimension": "TF", "option_a": "Você valoriza mais...", "option_b": "consistência e equidade", "preference_a": "T"},
    {"id": 113, "dimension": "JP", "option_a": "Você prefere...", "option_b": "trabalho bem estruturado e organizado", "preference_a": "J"},
    {"id": 114, "dimension": "EI", "option_a": "Você tende a...", "option_b": "tomar a iniciativa nas conversas", "preference_a": "E"},
    {"id": 115, "dimension": "SN", "option_a": "Você foca mais em...", "option_b": "fatos verificáveis", "preference_a": "S"},
    {"id": 116, "dimension": "TF", "option_a": "Ao decidir, você...", "option_b": "prioriza o raciocínio lógico", "preference_a": "T"},
    {"id": 117, "dimension": "JP", "option_a": "Você gosta de...", "option_b": "se organizar com antecedência", "preference_a": "J"},
    {"id": 118, "dimension": "EI", "option_a": "Você prefere...", "option_b": "discursos improvisados", "preference_a": "E"},
    {"id": 119, "dimension": "SN", "option_a": "Você confia mais em...", "option_b": "experiências práticas e vividas", "preference_a": "S"},
    {"id": 120, "dimension": "TF", "option_a": "Você tende a...", "option_b": "ser justo e imparcial com todos", "preference_a": "T"},
    {"id": 121, "dimension": "JP", "option_a": "Você prefere...", "option_b": "terminar tudo antes de comemorar", "preference_a": "J"},
    {"id": 122, "dimension": "EI", "option_a": "Você tende a...", "option_b": "falar abertamente em público", "preference_a": "E"},
    {"id": 123, "dimension": "SN", "option_a": "Você foca mais em...", "option_b": "o que é viável e prático", "preference_a": "S"},
    {"id": 124, "dimension": "TF", "option_a": "Você acredita que... é mais importante", "option_b": "os princípios", "preference_a": "T"},
    {"id": 125, "dimension": "JP", "option_a": "Você prefere...", "option_b": "cumprir horários rigorosamente", "preference_a": "J"},
    {"id": 126, "dimension": "EI", "option_a": "Em situações sociais, você...", "option_b": "gosta de ser o centro das atenções", "preference_a": "E"},
    {"id": 127, "dimension": "SN", "option_a": "Você prefere...", "option_b": "usar exemplos concretos", "preference_a": "S"},
    {"id": 128, "dimension": "TF", "option_a": "Ao decidir, você...", "option_b": "considera fatores objetivos", "preference_a": "T"},
    {"id": 129, "dimension": "JP", "option_a": "Você prefere...", "option_b": "seguir uma rotina estabelecida", "preference_a": "J"},
    {"id": 130, "dimension": "EI", "option_a": "Você gosta de...", "option_b": "organizar e conduzir eventos", "preference_a": "E"},
    {"id": 131, "dimension": "SN", "option_a": "Você foca mais em...", "option_b": "dados reais e autênticos", "preference_a": "S"},
    {"id": 132, "dimension": "TF", "option_a": "Você valoriza mais...", "option_b": "o julgamento racional", "preference_a": "T"},
    {"id": 133, "dimension": "JP", "option_a": "Você tende a...", "option_b": "planejar com bastante antecedência", "preference_a": "J"},
    {"id": 134, "dimension": "EI", "option_a": "Você prefere...", "option_b": "discussões com várias pessoas", "preference_a": "E"},
    {"id": 135, "dimension": "SN", "option_a": "Você confia mais em...", "option_b": "fatos já conhecidos e estabelecidos", "preference_a": "S"},
    {"id": 136, "dimension": "TF", "option_a": "Você acredita que... é mais importante", "option_b": "a exatidão e correção", "preference_a": "T"},
    {"id": 137, "dimension": "JP", "option_a": "Você prefere...", "option_b": "concluir as tarefas iniciadas", "preference_a": "J"},
    {"id": 138, "dimension": "EI", "option_a": "Você aprende mais através...", "option_b": "de discussões e troca de ideias", "preference_a": "E"},
    {"id": 139, "dimension": "SN", "option_a": "Você foca mais em...", "option_b": "problemas existentes e concretos", "preference_a": "S"},
    {"id": 140, "dimension": "TF", "option_a": "Ao decidir, você...", "option_b": "analisa todas as alternativas disponíveis", "preference_a": "T"},
    {"id": 141, "dimension": "JP", "option_a": "Você prefere...", "option_b": "trabalhos com prazos definidos", "preference_a": "J"},
    {"id": 142, "dimension": "EI", "option_a": "Você gosta de...", "option_b": "conhecer pessoas novas", "preference_a": "E"},
    {"id": 143, "dimension": "SN", "option_a": "Você prefere...", "option_b": "confiar na sua experiência anterior", "preference_a": "S"},
    {"id": 144, "dimension": "JP", "option_a": "Você tende a...", "option_b": "ter objetivos muito claros", "preference_a": "J"},
]

# Add more questions for version 200 (extend with 56 more questions)
QUESTIONS[200] = QUESTIONS[144].copy() + [
    {"id": 145, "dimension": "EI", "option_a": "Você prefere...", "option_b": "fazer apresentações em público", "preference_a": "E"},
    {"id": 146, "dimension": "SN", "option_a": "Você foca mais em...", "option_b": "problemas práticos do dia a dia", "preference_a": "S"},
    {"id": 147, "dimension": "TF", "option_a": "Você valoriza mais...", "option_b": "critérios objetivos e mensuráveis", "preference_a": "T"},
    {"id": 148, "dimension": "JP", "option_a": "Você prefere...", "option_b": "planos bem definidos e estruturados", "preference_a": "J"},
    {"id": 149, "dimension": "EI", "option_a": "Socializar faz você se sentir...", "option_b": "animado e cheio de energia", "preference_a": "E"},
    {"id": 150, "dimension": "SN", "option_a": "Você confia mais em...", "option_b": "evidências concretas e palpáveis", "preference_a": "S"},
    {"id": 151, "dimension": "TF", "option_a": "Você acredita que... mede melhor o sucesso", "option_b": "resultados e eficiência", "preference_a": "T"},
    {"id": 152, "dimension": "JP", "option_a": "Você prefere...", "option_b": "estar preparado para tudo", "preference_a": "J"},
    {"id": 153, "dimension": "EI", "option_a": "Você tende a...", "option_b": "socializar ativamente", "preference_a": "E"},
    {"id": 154, "dimension": "SN", "option_a": "Você foca mais em...", "option_b": "situações reais e concretas", "preference_a": "S"},
    {"id": 155, "dimension": "TF", "option_a": "Ao decidir, você...", "option_b": "analisa relações de causa e efeito", "preference_a": "T"},
    {"id": 156, "dimension": "JP", "option_a": "Você prefere...", "option_b": "abordagens estruturadas e metódicas", "preference_a": "J"},
    {"id": 157, "dimension": "EI", "option_a": "Você gosta de...", "option_b": "falar em reuniões e conferências", "preference_a": "E"},
    {"id": 158, "dimension": "SN", "option_a": "Você prefere...", "option_b": "resolver problemas específicos", "preference_a": "S"},
    {"id": 159, "dimension": "TF", "option_a": "Você valoriza mais...", "option_b": "padrões consistentes e uniformes", "preference_a": "T"},
    {"id": 160, "dimension": "JP", "option_a": "Você tende a...", "option_b": "cumprir prazos rigorosamente", "preference_a": "J"},
    {"id": 161, "dimension": "EI", "option_a": "Você ganha energia através...", "option_b": "de encontros e confraternizações", "preference_a": "E"},
    {"id": 162, "dimension": "SN", "option_a": "Você confia mais em...", "option_b": "dados estatísticos reais", "preference_a": "S"},
    {"id": 163, "dimension": "TF", "option_a": "Você acredita que... é mais importante", "option_b": "regras justas e imparciais", "preference_a": "T"},
    {"id": 164, "dimension": "JP", "option_a": "Você prefere...", "option_b": "listas de tarefas e checklists", "preference_a": "J"},
    {"id": 165, "dimension": "EI", "option_a": "Em festas e confraternizações, você...", "option_b": "lidera as conversas", "preference_a": "E"},
    {"id": 166, "dimension": "SN", "option_a": "Você foca mais em...", "option_b": "métodos e abordagens conhecidas", "preference_a": "S"},
    {"id": 167, "dimension": "TF", "option_a": "Ao decidir, você...", "option_b": "se baseia em fatos e evidências", "preference_a": "T"},
    {"id": 168, "dimension": "JP", "option_a": "Você prefere...", "option_b": "seguir o plano estabelecido", "preference_a": "J"},
    {"id": 169, "dimension": "EI", "option_a": "Você gosta de...", "option_b": "conversas espontâneas e improvisadas", "preference_a": "E"},
    {"id": 170, "dimension": "SN", "option_a": "Você prefere...", "option_b": "se basear na sua vivência prática", "preference_a": "S"},
    {"id": 171, "dimension": "TF", "option_a": "Você valoriza mais...", "option_b": "lógica sólida e evidências", "preference_a": "T"},
    {"id": 172, "dimension": "JP", "option_a": "Você tende a...", "option_b": "se programar com antecedência", "preference_a": "J"},
    {"id": 173, "dimension": "EI", "option_a": "Você prefere...", "option_b": "sessões de brainstorming em grupo", "preference_a": "E"},
    {"id": 174, "dimension": "SN", "option_a": "Você foca mais em...", "option_b": "o que é prático e exequível", "preference_a": "S"},
    {"id": 175, "dimension": "TF", "option_a": "Você acredita que... é mais importante", "option_b": "princípios e ordem", "preference_a": "T"},
    {"id": 176, "dimension": "JP", "option_a": "Você prefere...", "option_b": "concluir metas e objetivos", "preference_a": "J"},
    {"id": 177, "dimension": "EI", "option_a": "Você tende a...", "option_b": "tomar a iniciativa em atividades", "preference_a": "E"},
    {"id": 178, "dimension": "SN", "option_a": "Você prefere...", "option_b": "provar as coisas com fatos", "preference_a": "S"},
    {"id": 179, "dimension": "TF", "option_a": "Ao decidir, você...", "option_b": "prioriza o raciocínio lógico", "preference_a": "T"},
    {"id": 180, "dimension": "JP", "option_a": "Você prefere...", "option_b": "trabalhar de forma organizada", "preference_a": "J"},
    {"id": 181, "dimension": "EI", "option_a": "Você gosta de...", "option_b": "se expressar em meio a muitas pessoas", "preference_a": "E"},
    {"id": 182, "dimension": "SN", "option_a": "Você foca mais em...", "option_b": "pequenos detalhes específicos", "preference_a": "S"},
    {"id": 183, "dimension": "TF", "option_a": "Você valoriza mais...", "option_b": "análise objetiva e imparcial", "preference_a": "T"},
    {"id": 184, "dimension": "JP", "option_a": "Você tende a...", "option_b": "fazer planos detalhados", "preference_a": "J"},
    {"id": 185, "dimension": "EI", "option_a": "Você prefere...", "option_b": "agir por impulso e espontaneamente", "preference_a": "E"},
    {"id": 186, "dimension": "SN", "option_a": "Você prefere...", "option_b": "confiar no que já é conhecido", "preference_a": "S"},
    {"id": 187, "dimension": "TF", "option_a": "Ao decidir, você...", "option_b": "considera todos os fatores envolvidos", "preference_a": "T"},
    {"id": 188, "dimension": "JP", "option_a": "Você prefere...", "option_b": "objetivos claros e específicos", "preference_a": "J"},
    {"id": 189, "dimension": "EI", "option_a": "Você gosta de...", "option_b": "moderar e conduzir debates", "preference_a": "E"},
    {"id": 190, "dimension": "SN", "option_a": "Você foca mais em...", "option_b": "dados já existentes e disponíveis", "preference_a": "S"},
    {"id": 191, "dimension": "TF", "option_a": "Você valoriza mais...", "option_b": "racionalidade e justiça", "preference_a": "T"},
    {"id": 192, "dimension": "JP", "option_a": "Você tende a...", "option_b": "seguir horários e cronogramas", "preference_a": "J"},
    {"id": 193, "dimension": "EI", "option_a": "Você ganha energia através...", "option_b": "de atividades sociais e encontros", "preference_a": "E"},
    {"id": 194, "dimension": "SN", "option_a": "Você confia mais em...", "option_b": "observações práticas e diretas", "preference_a": "S"},
    {"id": 195, "dimension": "TF", "option_a": "Você acredita que... é mais importante", "option_b": "eficiência e lógica", "preference_a": "T"},
    {"id": 196, "dimension": "JP", "option_a": "Você prefere...", "option_b": "trabalhar com estruturas definidas", "preference_a": "J"},
    {"id": 197, "dimension": "EI", "option_a": "Você tende a...", "option_b": "participar ativamente de eventos sociais", "preference_a": "E"},
    {"id": 198, "dimension": "SN", "option_a": "Você foca mais em...", "option_b": "fatos do presente momento", "preference_a": "S"},
    {"id": 199, "dimension": "TF", "option_a": "Ao decidir, você...", "option_b": "prioriza fatores objetivos e mensuráveis", "preference_a": "T"},
    {"id": 200, "dimension": "JP", "option_a": "Você prefere...", "option_b": "organização e planejamento", "preference_a": "J"},
]


def get_questions(version: int = 70) -> list:
    """Get questions for specified version (70, 93, 144, or 200)"""
    if version not in QUESTIONS:
        version = 70
    return QUESTIONS[version]


def get_question_count(version: int = 70) -> int:
    """Get question count for version"""
    return len(get_questions(version))
